name: DEPLOY
on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: load trunk
      uses: jetli/trunk-action@v0.4.0
      with:
        version: 'v0.16.0'
    - name: build trunk release
      run: make prod
    - name: upload dist 
      uses: actions/upload-artifact@v3
      with:
        name: dist
        path: |
          dist/*
  # deploy_app:
  #   needs: build_trunk
  #   runs-on: ubuntu-latest
  #   steps:
  #   - uses: actions/checkout@v3
  #   - name: rsync upload dist
  #     uses: burnett01/rsync-deployments@6.0.0
  #     with:
  #       switches: -vzr --delete
  #       path: conf.d/
  #       remote_path: /home/www-data/web_bench/
  #       remote_host: ${{ secrets.HOST }}
  #       remote_user: ${{ secrets.USERNAME }}
  #       remote_key: ${{ secrets.DEPLOY_KEY }}
