name: DEPLOY
on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: load trunk
      uses: jetli/trunk-action@v0.4.0
      with:
        version: 'v0.16.0'
    - name: checkout
      uses: actions/checkout@v4
    - name: go to workspace
      run: cd ${GITHUB_WORKSPACE}
    - name: add wasm32 target
      run: rustup target add wasm32-unknown-unknown
    - name: build trunk release
      run: trunk build --release
    - name: rsync upload dist on server
      uses: burnett01/rsync-deployments@6.0.0
      with:
        switches: -vzr --delete
        path: dist/
        remote_path: /home/www-data/web_bench/dist
        remote_host: ${{ secrets.HOST }}
        remote_user: ${{ secrets.USERNAME }}
        remote_key: ${{ secrets.DEPLOY_KEY }}
    # - name: upload dist 
    #   uses: actions/upload-artifact@v3
    #   with:
    #     name: dist
    #     path: |
    #       dist/*
